name: Auto Click Streamlit

on:
  schedule:
    - cron: '0 */12 * * *'   # 每12小时执行一次
  workflow_dispatch:

jobs:
  clicker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # 关闭默认 GITHUB_TOKEN 的权限

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install selenium webdriver-manager

    - name: Run auto click script
      run: python auto_click.py

    - name: Commit and push log
      env:
        MY_PAT: ${{ secrets.MY_PAT }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        if [ ! -f click_log.txt ]; then
          echo "初始化日志文件于 $(date '+%Y-%m-%d %H:%M:%S')" > click_log.txt
        fi

        git add click_log.txt

        if git diff --cached --quiet; then
          echo "无变化，无需提交"
        else
          git commit -m "更新日志: $(date '+%Y-%m-%d %H:%M:%S')"
          git push https://x-access-token:${MY_PAT}@github.com/${{ github.repository }}.git HEAD:main
        fi
